# /.azure-pipelines/msdo-static-scan.yml
# Static security scan for .NET + React using Microsoft Security DevOps (MSDO)

trigger:
  branches:
    include: [ main ]
pr:
  branches:
    include: [ main, develop, feature/* ]

pool:
  vmImage: 'ubuntu-latest'  
variables:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '23.x'
  BUILD_CONFIGURATION: 'Release'
  SOLUTION: 'backend/*.sln'

steps:
  - checkout: self
    fetchDepth: 0

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '$(DOTNET_VERSION)'

  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'

  # Build so BinSkim can analyze binaries
  - script: |
      dotnet restore $(SOLUTION)
      dotnet build $(SOLUTION) -c $(BUILD_CONFIGURATION) --no-restore
    displayName: 'Restore & Build (.NET)'

  # --- Install scanners
  - script: |
      # DevSkim (SAST patterns for many languages)
      dotnet tool install -g Microsoft.CST.DevSkim.CLI
      echo '##vso[task.prependpath]$HOME/.dotnet/tools'

      # BinSkim (binary hardening checks)
      dotnet tool install -g Microsoft.CodeAnalysis.BinSkim

      # ESLint + security plugins
      npm i -D eslint eslint-plugin-security eslint-plugin-react eslint-plugin-jsx-a11y eslint-plugin-no-unsanitized

      # Trivy (deps/secrets/misconfig)
      sudo apt-get update -y
      sudo apt-get install -y wget
      wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
      echo "deb https://aquasecurity.github.io/trivy-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/trivy.list
      sudo apt-get update -y && sudo apt-get install -y trivy
    displayName: 'Install security tools'

  # --- Run scanners (emit SARIF)
  - script: |
      mkdir -p CodeAnalysisLogs

      # DevSkim
      devskim analyze --output CodeAnalysisLogs/devskim.sarif --ignore-globs node_modules/** --severity medium || true

      # ESLint (React/TS)
      npx eslint "src/**/*.{js,jsx,ts,tsx}" -f sarif -o CodeAnalysisLogs/eslint.sarif || true

      # BinSkim (scan built artifacts)
      binskim analyze "$(Build.SourcesDirectory)/**/bin/**" --recurse --output CodeAnalysisLogs/binskim.sarif || true

      # Trivy filesystem scan (deps, secrets, misconfig)
      trivy fs --scanners vuln,secret,misconfig --format sarif -o CodeAnalysisLogs/trivy.sarif .
    displayName: 'Run SAST & artifact scans'
    continueOnError: true

  # Publish SARIF for download / dashboards
  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: 'CodeAnalysisLogs'
      ArtifactName: 'CodeAnalysisLogs'
      publishLocation: 'Container'
