# /.azure-pipelines/msdo-static-scan.yml
# Static security scan for .NET + React using Microsoft Security DevOps (MSDO)

trigger:
  branches:
    include: [ main ]
pr:
  branches:
    include: [ main, develop, feature/* ]

pool:
  vmImage: 'ubuntu-latest'  
variables:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '23.x'
  BUILD_CONFIGURATION: 'Release'
  SOLUTION: 'backend/*.sln'

steps:
  - checkout: self
    fetchDepth: 0

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '$(DOTNET_VERSION)'

  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'

  # Build so BinSkim can analyze binaries
  - script: |
      dotnet restore $(SOLUTION)
      dotnet build $(SOLUTION) -c $(BUILD_CONFIGURATION) --no-restore
    displayName: 'Restore & Build (.NET)'

  # Run .NET tests with code coverage
  - script: |
      mkdir -p TestResults
      dotnet test $(SOLUTION) \
        --configuration $(BUILD_CONFIGURATION) \
        --no-build \
        --collect:"XPlat Code Coverage" \
        --results-directory TestResults \
        --logger trx \
        --settings backend/CodeCoverage.runsettings
    displayName: 'Run .NET Tests with Coverage'
    continueOnError: true

  # Install ReportGenerator for coverage reports
  - script: |
      dotnet tool install -g dotnet-reportgenerator-globaltool
      echo '##vso[task.prependpath]$HOME/.dotnet/tools'
    displayName: 'Install ReportGenerator'

  # Generate HTML coverage report
  - script: |
      # Find the coverage files (they're in GUID-named directories)
      COVERAGE_FILES=$(find TestResults -name "coverage.cobertura.xml" -type f)
      
      if [ -z "$COVERAGE_FILES" ]; then
        echo "No coverage files found!"
        exit 1
      fi
      
      echo "Found coverage files: $COVERAGE_FILES"
      
      # Convert newline-separated list to semicolon-separated for ReportGenerator
      COVERAGE_REPORTS=$(echo "$COVERAGE_FILES" | tr '\n' ';' | sed 's/;$//')
      
      echo "Coverage reports parameter: $COVERAGE_REPORTS"
      
      # Generate the report using found files
      reportgenerator \
        -reports:"$COVERAGE_REPORTS" \
        -targetdir:"TestResults/CoverageReport" \
        -reporttypes:"Cobertura;XMLSummary"
    displayName: 'Generate Coverage Report'
    condition: succeededOrFailed()

  # Publish test results
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'TestResults/**/*.trx'
      publishRunAttachments: true

  # Publish code coverage results
  - task: PublishCodeCoverageResults@2
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'TestResults/CoverageReport/Cobertura.xml'
      pathToSources: 'backend/src/'
      failIfCoverageEmpty: false

  # Alternative: Try to publish original coverage files if ReportGenerator fails
  - task: PublishCodeCoverageResults@2
    condition: failed()
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'TestResults/**/coverage.cobertura.xml'
      pathToSources: 'backend/src/'
      failIfCoverageEmpty: false

  # --- Frontend tests and coverage
  - script: |
      cd frontend
      echo "Installing frontend dependencies..."
      npm ci
    displayName: 'Install Frontend Dependencies'

  - script: |
      cd frontend
      echo "Running frontend tests with coverage..."
      npm run test -- run --coverage
    displayName: 'Run Frontend Tests with Coverage'
    continueOnError: true

  # Publish frontend test results
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'frontend/test-results.xml'
      testRunTitle: 'Frontend Tests'
      publishRunAttachments: true
    continueOnError: true

  # Publish frontend code coverage
  - task: PublishCodeCoverageResults@2
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'frontend/coverage/cobertura-coverage.xml'
      pathToSources: 'frontend/src/'
      failIfCoverageEmpty: false

  # --- Install scanners
  - script: |
      # DevSkim (SAST patterns for many languages)
      dotnet tool install -g Microsoft.CST.DevSkim.CLI
      echo '##vso[task.prependpath]$HOME/.dotnet/tools'

      # BinSkim (binary hardening checks) - alternative installation
      # Try different versions or skip if problematic
      dotnet tool install -g Microsoft.CodeAnalysis.BinSkim --version 1.9.4 || \
      dotnet tool install -g Microsoft.CodeAnalysis.BinSkim --version 1.8.0 || \
      echo "BinSkim installation failed, skipping binary analysis"

      # ESLint + security plugins
      npm i -D eslint eslint-plugin-security eslint-plugin-react eslint-plugin-jsx-a11y eslint-plugin-no-unsanitized

      # Trivy (deps/secrets/misconfig)
      sudo apt-get update -y
      sudo apt-get install -y wget apt-transport-https gnupg lsb-release
      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
      echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
      sudo apt-get update -y && sudo apt-get install -y trivy
    displayName: 'Install security tools'

  # --- Run scanners (emit SARIF)
  - script: |
      mkdir -p CodeAnalysisLogs
      
      echo "Starting security scans with verbose output..."

      # DevSkim
      echo "Running DevSkim SAST scan..."
      # Add timeout to prevent hanging and exclude problematic file types
      timeout 600s devskim analyze --source-code ./backend/src --output-file CodeAnalysisLogs/devskim-backend.sarif --file-format sarif --severity Critical,Important --ignore-globs "**/*.xml,**/*.csproj,**/*.sln,**/*.json" || echo "DevSkim backend scan timed out or failed"
      timeout 600s devskim analyze --source-code ./frontend/src --output-file CodeAnalysisLogs/devskim-frontend.sarif --file-format sarif --severity Critical,Important --ignore-globs "**/*.xml,**/*.json,**/*.config" || echo "DevSkim frontend scan timed out or failed"
      
      # Combine results if both exist
      if [ -f CodeAnalysisLogs/devskim-backend.sarif ] && [ -f CodeAnalysisLogs/devskim-frontend.sarif ]; then
        # For now, just use backend results as primary
        cp CodeAnalysisLogs/devskim-backend.sarif CodeAnalysisLogs/devskim.sarif
      elif [ -f CodeAnalysisLogs/devskim-backend.sarif ]; then
        cp CodeAnalysisLogs/devskim-backend.sarif CodeAnalysisLogs/devskim.sarif
      elif [ -f CodeAnalysisLogs/devskim-frontend.sarif ]; then
        cp CodeAnalysisLogs/devskim-frontend.sarif CodeAnalysisLogs/devskim.sarif
      else
        # Create empty SARIF if no results
        echo "DevSkim scan failed, creating empty SARIF"
        echo '{"version":"2.1.0","runs":[{"tool":{"driver":{"name":"DevSkim","version":"failed"}},"results":[]}]}' > CodeAnalysisLogs/devskim.sarif
      fi

      # ESLint (React/TS)
      cd frontend
      echo "Running ESLint security scan..."
      # Create minimal eslint config if none exists
      if [ ! -f .eslintrc.js ] && [ ! -f .eslintrc.json ]; then
        echo '{"extends": ["eslint:recommended"], "plugins": ["security"], "env": {"browser": true, "es2021": true}, "parserOptions": {"ecmaVersion": 12, "sourceType": "module"}}' > .eslintrc.json
      fi
      npx eslint "src/**/*.{js,jsx,ts,tsx}" -f sarif -o ../CodeAnalysisLogs/eslint.sarif || true
      cd ..

      # BinSkim (scan built artifacts)
      echo "Running BinSkim binary analysis..."
      if command -v binskim &> /dev/null; then
        binskim analyze "$(Build.SourcesDirectory)/**/bin/**" --recurse --output CodeAnalysisLogs/binskim.sarif || true
      else
        echo "BinSkim not available, skipping binary analysis"
        echo '{"version":"2.1.0","runs":[{"tool":{"driver":{"name":"BinSkim","informationUri":"https://github.com/Microsoft/binskim","version":"skipped"}},"results":[]}]}' > CodeAnalysisLogs/binskim.sarif
      fi

      # Trivy filesystem scan (deps, secrets, misconfig)
      echo "Running Trivy vulnerability and security scan..."
      trivy fs --scanners vuln,secret,misconfig --format sarif -o CodeAnalysisLogs/trivy.sarif --severity HIGH,CRITICAL . || true
    displayName: 'Run SAST & artifact scans'
    continueOnError: true

  # Publish SARIF for download / dashboards
  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: 'CodeAnalysisLogs'
      ArtifactName: 'CodeAnalysisLogs'
      publishLocation: 'Container'
