name: BasicReleasePipelineWithBuildJob
trigger: none

parameters:
- name: poolName
  type: string
  default: Dependabot-HostedPool-WUS-2-Ubuntu

- name: image
  type: string
  default: --imageName--

- name: os
  type: string
  default: windows

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: ${{ parameters.poolName }}
      image: ${{ parameters.image }}
      os: ${{ parameters.os }}

    stages:
    - stage: stage1
      displayName: Stage 1
      jobs:
      - job: BuildJob
        displayName: Build Job
        # Remove templateContext and outputs if your pipeline does not publish any artifacts. Check here for more details: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/outputs
        templateContext:
          outputs:
          # Declare outputs here for efficient SDL analysis
          - output: pipelineArtifact
            targetPath: $(System.DefaultWorkingDirectory)/Samples
            artifactName: artifactName
        steps:
        # Add build steps below
        - checkout: self
        - powershell: echo "Hello World from Job"

      - job: release
        dependsOn: BuildJob
        templateContext:
          type: releaseJob
          isProduction: false
          inputs:
          # Declare inputs to be released here to ensure they receive relevant checks
          - input: pipelineArtifact
            artifactName: artifactName
        steps:
        # Add release steps below
        - script: tree.com $(Pipeline.Workspace) /f
          displayName: List files
