global using Xunit;
global using Moq;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Http;
global using MedBench.Core.Models;
global using MedBench.Core.Interfaces;
global using MedBench.API.Controllers;
global using System.Security.Claims;
global using System.Security.Principal; 